name: Glassdoor Scraper Node.js

on:
  schedule:
    - cron: '0 0 * * *' # Chạy 12h đêm mỗi ngày
  workflow_dispatch: # Cho phép chạy thủ công bằng nút bấm

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Script
        run: node scraper.js
        env:
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}